# Site settings
title:  Barming Youth FC
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
        The main website of the Barming Youth Football Club.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: barmingyouthfc
##github_username:  jekyll

# Build settings
markdown: kramdown

collections:
- events
